"use client";

import Link from "next/link";
import { useState } from "react";
import { ArrowLeft, ArrowRight, ExternalLink, FolderGit2, Loader2, Share2 } from "lucide-react";
import { useDashboard } from "@/context/dashboard-context";

type Filter = "all" | "proven" | "partial" | "claimed";

export default function EvidenceMatrixPage() {
  const { profile, resumeSkills, evidenceList, loading } = useDashboard();
  const [filter, setFilter] = useState<Filter>("all");
  const [selectedSkill, setSelectedSkill] = useState<string | null>(null);

  if (loading) return <div className="flex h-96 items-center justify-center gap-3 text-sm text-muted-text"><Loader2 className="w-5 h-5 animate-spin text-deep-green" />Loading your evidence report...</div>;

  const rows = resumeSkills.map((claim) => evidenceList.find((item) => item.skill_name.toLowerCase() === claim.skill_name.toLowerCase()) || { id: claim.id, skill_name: claim.skill_name, status: "claimed" as const, confidence_score: 0, evidence_summary: "This skill is listed on your resume but has not been evaluated against a repository yet.", matched_repos: [] });
  const filtered = rows.filter((row) => filter === "all" || row.status === filter);
  const selected = rows.find((row) => row.skill_name === selectedSkill);

  return <div className="space-y-8 page-enter">
    <header className="flex flex-col sm:flex-row sm:items-end justify-between gap-5 pb-7 border-b border-border"><div><Link href="/dashboard" className="inline-flex items-center gap-1 text-xs text-muted-text hover:text-ink mb-4"><ArrowLeft className="w-3.5 h-3.5" />Back to dashboard</Link><p className="text-sm font-semibold text-deep-green mb-2">Skill claims to evidence</p><h1 className="font-heading text-3xl sm:text-4xl font-bold tracking-[-0.04em]">Your evidence report</h1><p className="text-sm text-muted-text mt-2 max-w-xl">See exactly why each resume claim is proven, partial, or still unsupported.</p></div>{profile?.share_slug && <Link href={`/v/${profile.share_slug}`} target="_blank" className="inline-flex items-center gap-2 text-sm font-semibold text-deep-green"><Share2 className="w-4 h-4" />Share report</Link>}</header>
    <div className="flex flex-wrap gap-2">{(["all", "proven", "partial", "claimed"] as Filter[]).map((item) => <button key={item} type="button" onClick={() => setFilter(item)} className={`px-3 py-2 rounded-sm border text-sm font-medium transition-colors ${filter === item ? "bg-deep-green text-white border-deep-green" : "bg-paper border-border text-muted-text hover:text-ink"}`}>{item === "claimed" ? "Claimed-only" : item.charAt(0).toUpperCase() + item.slice(1)}</button>)}</div>
    {!rows.length ? <div className="border border-border bg-paper p-8 sm:p-12"><h2 className="font-heading text-xl font-bold">Your evidence report is not ready yet.</h2><p className="text-sm text-muted-text mt-2 max-w-lg">Upload your resume and connect GitHub. SkillProof will compare your claimed skills with evidence from your public work.</p><Link href="/onboarding" className="inline-flex items-center gap-2 mt-5 text-sm font-semibold text-deep-green">Start analysis <ArrowRight className="w-4 h-4" /></Link></div> : <div className="border-y border-border bg-paper overflow-x-auto"><table className="w-full min-w-170 text-left text-sm"><thead className="border-b border-border text-xs text-muted-text"><tr><th className="py-3 px-4 font-medium">Skill</th><th className="py-3 px-4 font-medium">Resume claim</th><th className="py-3 px-4 font-medium">Evidence</th><th className="py-3 px-4 font-medium">Status</th><th className="py-3 px-4 font-medium">Open</th></tr></thead><tbody className="divide-y divide-border">{filtered.map((row) => <tr key={row.id} className="hover:bg-warm-ivory/60"><td className="py-4 px-4 font-semibold">{row.skill_name}</td><td className="py-4 px-4 text-muted-text max-w-55">Resume skill claim</td><td className="py-4 px-4 text-muted-text">{row.matched_repos?.length ? `${row.matched_repos.length} ${row.matched_repos.length === 1 ? "repository" : "repositories"}` : "No supporting evidence"}</td><td className="py-4 px-4"><span className={`text-[10px] font-bold tracking-wide px-2 py-1 rounded-md ${row.status === "proven" ? "bg-status-proven/10 text-status-proven" : row.status === "partial" ? "bg-status-partial/10 text-status-partial" : "bg-status-claimed/10 text-status-claimed"}`}>{row.status === "claimed" ? "CLAIMED-ONLY" : row.status.toUpperCase()}</span></td><td className="py-4 px-4"><button type="button" onClick={() => setSelectedSkill(selectedSkill === row.skill_name ? null : row.skill_name)} className="text-deep-green font-semibold text-xs">{selectedSkill === row.skill_name ? "Close" : "View evidence"}</button></td></tr>)}</tbody></table></div>}
    {selected && <section className="border border-border bg-paper p-5 sm:p-7"><div className="flex flex-col sm:flex-row sm:items-start justify-between gap-4"><div><p className="text-sm font-semibold text-deep-green">{selected.status.toUpperCase()}</p><h2 className="font-heading text-2xl font-bold mt-1">{selected.skill_name}</h2></div><p className="text-sm text-muted-text">Confidence {Math.round(Number(selected.confidence_score) * 100)}%</p></div><div className="mt-6 grid lg:grid-cols-[0.8fr_1.2fr] gap-8"><div><h3 className="text-sm font-semibold">Why this status</h3><p className="text-sm text-muted-text leading-6 mt-2">{selected.evidence_summary || "No explanation was stored for this result."}</p></div><div><h3 className="text-sm font-semibold">Evidence sources</h3>{selected.matched_repos?.length ? <div className="mt-3 space-y-2">{selected.matched_repos.map((repo) => <div key={repo.url} className="flex items-center justify-between gap-3 border-b border-border py-3"><div className="min-w-0"><a href={repo.url} target="_blank" rel="noreferrer" className="flex items-center gap-2 text-sm font-semibold hover:text-deep-green truncate"><FolderGit2 className="w-4 h-4 text-deep-green shrink-0" />{repo.name}<ExternalLink className="w-3 h-3 shrink-0" /></a><p className="text-xs text-muted-text mt-1">{repo.last_commit_at ? `Recent activity ${new Date(repo.last_commit_at).toLocaleDateString()}` : "Commit activity unavailable"}</p></div><span className="text-xs text-muted-text">{repo.has_tests ? "Tests detected" : "No tests detected"}</span></div>)}</div> : <p className="text-sm text-muted-text mt-2">No repositories matched this claim. No repository evidence is available to show.</p>}</div></div></section>}
  </div>;
}
